# Generated by Django 3.0.6 on 2020-05-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrinho', models.CharField(max_length=50)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField(default=1)),
                ('presente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presente.Presente')),
            ],
            options={
                'db_table': 'itens_carrinho',
                'ordering': ['data_adicao'],
            },
        ),
    ]
