# Generated by Django 3.0.6 on 2020-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='presentes/imagens')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='presentes/thumbnail')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
    ]
